doc-store-build:
  image: microsoft/aspnetcore-build:1.0.1-projectjson
  environment:
      HTTP_PROXY: http://proxyseso.scania.com:8080
      HTTPS_PROXY: http://proxyseso.scania.com:8080
  volumes:
  # mounting current dir on local machine to sln directory in container
    - .:/sln 
  working_dir: /sln
  entrypoint: ["sh", "./build-container.sh"]
